import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import RestaurantList from "../components/RestaurantList";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>What&apos;s for dinner </title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <RestaurantList />
      </main>
    </div>
  );
};

export default Home;
